# Generated by Django 4.1.5 on 2023-01-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-16 07:20:23.864863'),
            preserve_default=False,
        ),
    ]
