# Generated by Django 4.1.5 on 2023-01-23 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('tracked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_user_article_set', to=settings.AUTH_USER_MODEL)),
                ('tracking_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_user_article_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
