# Generated by Django 4.1.5 on 2023-02-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_follow_is_friends_and_more'),
        ('user', '0002_alter_profile_email'),
    ]

    operations = [
    ]
