# Generated by Django 4.1.5 on 2023-01-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_follow_is_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='is_friends',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
